import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import { Toaster } from "@/components/Others/ToasterComponent/ToasterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SuperIt || NextJS",
  description: "Generated by Abdur Rahman",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <div className="container mx-auto flex flex-col justify-between">
            <Navbar></Navbar>
            <div>{children}</div>
            <Footer></Footer>
          </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
